# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eeia < Formula
  desc "EEIA coding challenges CLI"
  homepage "https://eeiachallenges.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ML-for-B-E/eeia-challenges-cli/releases/download/v0.1.0/eeia_0.1.0_darwin_amd64.tar.gz"
      sha256 "cb05fb1cf47ce4848caee20f4df5a697a969623f8bce720eb0d27b6a03637d52"

      define_method(:install) do
        bin.install "eeia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ML-for-B-E/eeia-challenges-cli/releases/download/v0.1.0/eeia_0.1.0_darwin_arm64.tar.gz"
      sha256 "b24351c290c97830a3348db40040de1f70c4b2f8c626d282e5d69fd319435a66"

      define_method(:install) do
        bin.install "eeia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ML-for-B-E/eeia-challenges-cli/releases/download/v0.1.0/eeia_0.1.0_linux_amd64.tar.gz"
      sha256 "a073ad87a1a81a1e74951457c3e4eaf6e145931cb17ad7560f49b78b80ca0a8c"
      define_method(:install) do
        bin.install "eeia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ML-for-B-E/eeia-challenges-cli/releases/download/v0.1.0/eeia_0.1.0_linux_arm64.tar.gz"
      sha256 "f7876ab2292af69ec704def0d3c5b0a1d440c4dc3d580fdbd97eb51714669dcb"
      define_method(:install) do
        bin.install "eeia"
      end
    end
  end

  test do
    system "#{bin}/eeia --version"
  end
end
