# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eeia < Formula
  desc "EEIA coding challenges CLI"
  homepage "https://eeiachallenges.com"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ML-for-B-E/homebrew-eeia-challenges-cli/releases/download/v0.1.1/eeia_0.1.1_darwin_amd64.tar.gz"
      sha256 "81c1f3715a221ebf8bd27b364ec778d84749b14b55602b5505382f5e2a8e46e1"

      define_method(:install) do
        bin.install "eeia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ML-for-B-E/homebrew-eeia-challenges-cli/releases/download/v0.1.1/eeia_0.1.1_darwin_arm64.tar.gz"
      sha256 "cd1bb092d0fa2d4fccbe8b850ecc9b444a5d7caca269ce2ae5ecd0a474b2c812"

      define_method(:install) do
        bin.install "eeia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ML-for-B-E/homebrew-eeia-challenges-cli/releases/download/v0.1.1/eeia_0.1.1_linux_amd64.tar.gz"
      sha256 "ce7db409f6458569de04bfff46cd925eb56a2434f49d63a414222715bba7884c"
      define_method(:install) do
        bin.install "eeia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ML-for-B-E/homebrew-eeia-challenges-cli/releases/download/v0.1.1/eeia_0.1.1_linux_arm64.tar.gz"
      sha256 "f418b2cdcd6478dcd15ace475af0b28e87c2ba7bded6d177dffe76554bfb55f8"
      define_method(:install) do
        bin.install "eeia"
      end
    end
  end

  test do
    system "#{bin}/eeia --version"
  end
end
